#!/bin/bash
ssh ubuntu@3.94.55.99 <<EOF
    cd ~/test-node-app
    git pull
    curl -o-   https://raw.githubusercontent.com/creationix/nvm/v0.33.8/install.sh    | bash
    . ~/.nvm/nvm.sh
    nvm install v10.11.0
    npm set audit false
    npm install
    npm install -g nodemon pm2
    pm2 restart ecosystem.config.js
    exit
EOF
